version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=apidashboard
    ports:
      - "5432:5432"
    # BARIS INI SANGAT PENTING
    volumes:
      - postgres_data:/var/lib/postgresql/data

# BAGIAN INI JUGA SANGAT PENTING
volumes:
  postgres_data: